name: Run IPTV Scripts

on:
  schedule:
    - cron: '0 */6 * * *' # يشتغل تلقائياً كل 6 ساعات
  workflow_dispatch: # يخليك تشغلو بيدك وقت ما تحب

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Playlists Builders
      run: |
        python make_playlist.py
        python make_adult.py

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git commit -m "Update playlists and satellites" || exit 0
        git push
